# Converts the .npy files generated by later Eric's later qaoa program into text files read by the QAOA_Reptile Program
import numpy as np
A = np.load('data-49.npy', allow_pickle=True)
A = A.item()
A = A['adjacency']

B = np.argwhere(A)
file = open('savefile.txt', 'w')
file.write('Test case for Eric\'s program verification: 49 qubits.\n\n')
for i in range(B.shape[0]):
    file.write(str(B[i,0] + 1)+' '+str(B[i,1]+1)+' '+str(1.0)+'\n')
file.close()